version: "3.8"
services:
  testservice:
    build: testservice/
    ports:
      - "80"
    deploy:
      replicas: 2
    volumes:
      - log-volume:/var/log
  muck:
    build: .
    depends_on:
      - testservice
    volumes:
      - log-volume:/var/log
volumes:
  log-volume:
